### ISSUE TITLE
放到版本目录里了，但是直播姬打开的时候还是强制静音

### ISSUE THREAD

**Issue by LolitaOT** [SakuraKoi/FuckKookObs#1]
![image](https://github.com/SakuraKoi/FuckKookObs/assets/32677256/dca1ceb6-ebf7-4bfb-bf91-28832bddb8c8)
![image](https://github.com/SakuraKoi/FuckKookObs/assets/32677256/b36408cc-4888-4952-bc69-928683733510)

**Comment by SakuraKoi** [comment]
看看任务栏里kook的标题有没有被补丁修改, 确定一下生效没

**Comment by LochenDD** [comment]
![屏幕截图 2024-05-28 205907](https://github.com/SakuraKoi/FuckKookObs/assets/41977322/01ccf0e7-da7d-41e0-af4f-955fc7839ae8)
0.84.3版本 不生效了

**Comment by LolitaOT** [comment]
![image](https://github.com/SakuraKoi/FuckKookObs/assets/32677256/43e97062-4cb6-443f-a2da-4b140e808c95)
![image](https://github.com/SakuraKoi/FuckKookObs/assets/32677256/4e91b99e-1fcc-4ca5-826c-ea341951e8bd)
显示解锁了，但还是不行，不能取消静音

**Comment by SakuraKoi** [comment]
> ![屏幕截图 2024-05-28 205907](https://private-user-images.githubusercontent.com/41977322/334420662-01ccf0e7-da7d-41e0-af4f-955fc7839ae8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDE2NzUsIm5iZiI6MTcxNjkwMTM3NSwicGF0aCI6Ii80MTk3NzMyMi8zMzQ0MjA2NjItMDFjY2YwZTctZGE3ZC00MWUwLWFmNGYtOTU1ZmM3ODM5YWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDEzMDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNjI3OTcyYTM1MzUxZGRiYzhhMmZkMjM5NjZlY2M5Y2YzMGY1NDdlNzhlYTdlZDQ3NjliYzQ0MjYxMGYwMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-uoTO9FXmmOlsQKeoTHfh1LU2KuNbIh9-MbIKIDXpZU) 0.84.3版本 不生效了



> ![image](https://private-user-images.githubusercontent.com/32677256/334421660-43e97062-4cb6-443f-a2da-4b140e808c95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDE3NDcsIm5iZiI6MTcxNjkwMTQ0NywicGF0aCI6Ii8zMjY3NzI1Ni8zMzQ0MjE2NjAtNDNlOTcwNjItNGNiNi00NDNmLWEyZGEtNGIxNDBlODA4Yzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDEzMDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYjNhZjBhOGNhYmI3ZTNjMWJlNzE2MTIxNDRmODg0MGY0YjhhZTRkZTMwZmFkNGI1YWY4NmYzMmQzY2Q5YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LtYkPKK12A8N-S9ctvru8Bx3sJrnil3VGRjHW1Z0tYQ) ![image](https://private-user-images.githubusercontent.com/32677256/334421998-4e91b99e-1fcc-4ca5-826c-ea341951e8bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDE3NDcsIm5iZiI6MTcxNjkwMTQ0NywicGF0aCI6Ii8zMjY3NzI1Ni8zMzQ0MjE5OTgtNGU5MWI5OWUtMWZjYy00Y2E1LTgyNmMtZWEzNDE5NTFlOGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDEzMDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YzM2ODhmNTlhMWUwYmMxNzI0OTczYzRjNDVjYWI3MDgyMzdlZWU2NmEzN2Y5M2Q4OWE0Y2IxNTlkYjVlZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQ22uTxpbdzWaTPqPg9UzNYYzGp1AqSyHg8a2Xtk2jE) 显示解锁了，但还是不行，不能取消静音

咱去整个直播姬测试一下

**Comment by SakuraKoi** [comment]
有点意思 识别直播姬貌似不是简单的通过进程, 抓一下kook的windows api call看看

**Comment by SakuraKoi** [comment]
草, hook代码的bug, 被抓到的EnumWindows调用误导了半天, 一看Process32Next没拦截下来x
